import type { Application } from "./types";
import { scoreApplication } from "./scoring";

// Mock applications for the admin dashboard.
// In production, these come from the database via API.
const RAW_APPLICATIONS: Omit<Application, "scoreBreakdown" | "aiSummary">[] = [
  {
    id: "app-001",
    company: {
      name: "NeuroLink AI",
      website: "https://neurolink-ai.ch",
      shortDescription: "AI-powered early detection of neurodegenerative diseases",
      location: "Geneva, Switzerland",
      foundedDate: "2025-03",
      stage: "Prototype",
      revenueLast30d: "0",
      revenueLast12m: "0",
      detailedDescription:
        "Using AI-powered neural interfaces to detect early signs of neurodegenerative diseases. Current diagnostic tools miss early markers in 60% of cases.",
      differentiation:
        "Proprietary ML pipeline trained on 100K+ brain scans from HUG partnership. Non-invasive, 15-minute scan vs. current 2-hour MRI protocols.",
      isIncorporated: "Yes",
      customerTypes: ["B2B", "B2G"],
      productChannels: ["Desktop", "Hardware"],
      markets: "MedTech, AI, Healthcare",
    },
    team: [
      {
        id: "tm-001",
        firstName: "Clara",
        lastName: "Dubois",
        email: "clara@neurolink-ai.ch",
        role: "CEO",
        description: "8 years in MedTech, previously at Roche Diagnostics.",
        skills: "Business Strategy, MedTech, Fundraising",
        amazingBuild: "Led regulatory approval for 3 Class II medical devices at Roche.",
        linkedin: "https://linkedin.com/in/claradubois",
        phone: "+41 79 123 4567",
      },
      {
        id: "tm-002",
        firstName: "Pavel",
        lastName: "Novak",
        email: "pavel@neurolink-ai.ch",
        role: "CTO",
        description: "PhD Neuroscience EPFL, 15 publications in neural imaging.",
        skills: "Machine Learning, Neuroscience, Signal Processing",
        amazingBuild: "Published novel EEG signal processing method cited 200+ times.",
        linkedin: "https://linkedin.com/in/pavelnovak",
        phone: "+41 79 234 5678",
      },
    ],
    project: {
      problemStatement:
        "Current diagnostic tools for neurodegenerative diseases miss early markers in 60% of cases, leading to late interventions when treatment options are limited.",
      differentiation:
        "Non-invasive 15-minute scan using proprietary ML pipeline. Patent pending on signal processing method.",
      statusAchievements:
        "Prototype complete. Pilot agreement with HUG. Letter of intent from 3 Swiss clinics. 2 peer-reviewed publications.",
      raisingMoney: "Yes, actively",
      totalRaised: "CHF 50,000",
      runwayMonths: "8",
      investors: "Angel investors (CHF 50K pre-seed)",
    },
    marketIP: {
      intellectualProperty: "1 patent filed (PCT phase). Licensed dataset from UNIGE.",
      priorSupport: "Innosuisse feasibility study grant (CHF 25K). No previous FONGIT application.",
      researchOrgs: ["UNIGE", "HUG", "Campus Biotech"],
    },
    fongitFit: {
      genevaStatus: ["Based in Geneva"],
      permitDetails: "Swiss B permit.",
      howCanFongitHelp:
        "We need coaching to refine our go-to-market strategy and access to financing for our seed round.",
      supportSeeking: ["Coaching", "Access to Financing", "Incubator Hosting"],
      referralSource: "Dr. James Miners recommended we apply after meeting at Campus Biotech.",
      backupEmail: "clara.dubois@gmail.com",
    },
    documents: {
      pitchDeckUrl: "/uploads/neurolink-deck-v3.pdf",
      additionalDocsUrl: "/uploads/neurolink-exec-summary.pdf",
      productVideoUrl: "https://youtube.com/watch?v=example1",
      teamVideoUrl: "",
    },
    status: "new",
    score: null,
    internalNotes: "",
    submittedAt: "2026-02-28T10:30:00Z",
    updatedAt: "2026-02-28T10:30:00Z",
  },
  {
    id: "app-002",
    company: {
      name: "TerraSense",
      website: "https://terrasense.io",
      shortDescription: "IoT soil monitoring for precision agriculture",
      location: "Lausanne, Switzerland",
      foundedDate: "2024-09",
      stage: "Users",
      revenueLast30d: "CHF 3,200",
      revenueLast12m: "CHF 28,000",
      detailedDescription:
        "Network of low-cost soil sensors with AI-powered analytics platform for farmers and agribusinesses.",
      differentiation:
        "10x cheaper than existing solutions. Solar-powered sensors with 5-year battery life. ML models trained on Swiss alpine soil data.",
      isIncorporated: "Yes",
      customerTypes: ["B2B"],
      productChannels: ["Hardware", "Mobile", "API"],
      markets: "AgriTech, CleanTech, IoT",
    },
    team: [
      {
        id: "tm-003",
        firstName: "Marco",
        lastName: "Bellucci",
        email: "marco@terrasense.io",
        role: "CEO & Co-Founder",
        description: "Agricultural engineer with 5 years at Syngenta.",
        skills: "Agriculture, Hardware, Business Development",
        amazingBuild: "Designed crop monitoring system deployed across 200 Swiss farms.",
        linkedin: "https://linkedin.com/in/marcobellucci",
        phone: "+41 78 345 6789",
      },
    ],
    project: {
      problemStatement:
        "Swiss farmers lose an estimated CHF 500M annually from suboptimal irrigation and fertilization. Existing precision agriculture tools cost CHF 10K+ per hectare.",
      differentiation: "Sensor hardware at CHF 50/unit vs CHF 500+ competitors. Swiss-specific soil models.",
      statusAchievements: "12 paying farming clients. 500 sensors deployed. Revenue growing 30% MoM.",
      raisingMoney: "Yes, actively",
      totalRaised: "CHF 200,000",
      runwayMonths: "14",
      investors: "Climate Fund (CHF 150K), Angel (CHF 50K)",
    },
    marketIP: {
      intellectualProperty: "2 patents filed on sensor design. Proprietary firmware.",
      priorSupport: "Innosuisse grant (CHF 100K). EPFL Innovation Park resident.",
      researchOrgs: ["EPFL"],
    },
    fongitFit: {
      genevaStatus: ["Based near Geneva"],
      permitDetails: "Swiss C permit.",
      howCanFongitHelp: "Looking to scale manufacturing and expand into French-speaking Swiss market.",
      supportSeeking: ["Coaching", "Access to Financing", "Innovation Community"],
      referralSource: "Found FONGIT through Startupticker.",
      backupEmail: "marco.bellucci@proton.me",
    },
    documents: {
      pitchDeckUrl: "/uploads/terrasense-deck.pdf",
      additionalDocsUrl: null,
      productVideoUrl: "https://youtube.com/watch?v=example2",
      teamVideoUrl: "",
    },
    status: "review",
    score: 78,
    internalNotes: "Strong traction for early stage. Need to verify EPFL IP licensing terms.",
    submittedAt: "2026-02-25T14:15:00Z",
    updatedAt: "2026-02-27T09:00:00Z",
  },
  {
    id: "app-003",
    company: {
      name: "Quantum Mesh",
      website: "",
      shortDescription: "Post-quantum cryptography for IoT networks",
      location: "Geneva, Switzerland",
      foundedDate: "2025-11",
      stage: "Idea",
      revenueLast30d: "0",
      revenueLast12m: "0",
      detailedDescription:
        "Developing lightweight post-quantum encryption protocols optimized for resource-constrained IoT devices.",
      differentiation: "Novel lattice-based encryption that runs on microcontrollers with 32KB RAM.",
      isIncorporated: "No",
      customerTypes: ["B2B", "Licensing"],
      productChannels: ["API", "Server Software"],
      markets: "Cybersecurity, Deep Tech, IoT",
    },
    team: [
      {
        id: "tm-004",
        firstName: "Aisha",
        lastName: "Nkomo",
        email: "aisha@quantummesh.dev",
        role: "Founder",
        description: "PhD candidate in cryptography at UNIGE. Published at CRYPTO and EUROCRYPT.",
        skills: "Cryptography, Mathematics, Embedded Systems",
        amazingBuild: "Open-source post-quantum library with 2K GitHub stars.",
        linkedin: "https://linkedin.com/in/aishanmoko",
        phone: "+41 76 456 7890",
      },
    ],
    project: {
      problemStatement:
        "Quantum computers will break current IoT encryption within 5-10 years. Existing PQ solutions require too much memory for IoT devices.",
      differentiation: "10x memory reduction vs. NIST PQ standards. Academic backing from UNIGE crypto lab.",
      statusAchievements: "Academic proof of concept. Benchmarks published. Seeking to build commercial prototype.",
      raisingMoney: "Not yet",
      totalRaised: "0",
      runwayMonths: "0",
      investors: "",
    },
    marketIP: {
      intellectualProperty: "Algorithm published in open literature. Patent strategy under discussion with UNIGE.",
      priorSupport: "UNIGE doctoral funding. No external startup funding yet.",
      researchOrgs: ["UNIGE"],
    },
    fongitFit: {
      genevaStatus: ["Based in Geneva"],
      permitDetails: "Swiss B permit (academic).",
      howCanFongitHelp: "Need help transitioning from research to startup. Coaching on business model and incorporation.",
      supportSeeking: ["Project Initiation", "Coaching", "Innovation Community"],
      referralSource: "UNIGE Innovation Office recommended FONGIT.",
      backupEmail: "aisha.nkomo@unige.ch",
    },
    documents: {
      pitchDeckUrl: "/uploads/quantummesh-slides.pdf",
      additionalDocsUrl: "/uploads/quantummesh-paper.pdf",
      productVideoUrl: "",
      teamVideoUrl: "",
    },
    status: "review",
    score: 65,
    internalNotes: "Very early stage but strong academic foundation. Ideal for Innovation Initiation program.",
    submittedAt: "2026-02-20T08:45:00Z",
    updatedAt: "2026-02-22T16:30:00Z",
  },
  {
    id: "app-004",
    company: {
      name: "BioForge",
      website: "https://bioforge.bio",
      shortDescription: "Synthetic biology platform for sustainable materials",
      location: "Geneva, Switzerland",
      foundedDate: "2024-01",
      stage: "Paying Users",
      revenueLast30d: "CHF 45,000",
      revenueLast12m: "CHF 380,000",
      detailedDescription: "Engineering microorganisms to produce high-performance biodegradable polymers for packaging.",
      differentiation: "Only European platform with FDA-grade bio-polymer production at scale. 3 enterprise contracts.",
      isIncorporated: "Yes",
      customerTypes: ["B2B"],
      productChannels: ["Hardware"],
      markets: "BioTech, Sustainability, Materials Science",
    },
    team: [
      {
        id: "tm-005",
        firstName: "Lukas",
        lastName: "Meier",
        email: "lukas@bioforge.bio",
        role: "CEO",
        description: "Former McKinsey, PhD Molecular Biology ETH Zurich.",
        skills: "Strategy, Synthetic Biology, Fundraising",
        amazingBuild: "Raised CHF 500K pre-seed in 6 weeks.",
        linkedin: "https://linkedin.com/in/lukasmeier",
        phone: "+41 79 567 8901",
      },
    ],
    project: {
      problemStatement: "Global packaging industry produces 150M tons of plastic waste annually. Bio-alternatives are 5x more expensive.",
      differentiation: "Proprietary fermentation process reduces bio-polymer cost to 1.5x petroleum plastic. FDA-grade quality.",
      statusAchievements: "3 enterprise contracts. Revenue CHF 380K LTM. Pilot with major Swiss retailer.",
      raisingMoney: "Yes, actively",
      totalRaised: "CHF 500,000",
      runwayMonths: "10",
      investors: "Climate VC (CHF 300K), Swiss Angels (CHF 200K)",
    },
    marketIP: {
      intellectualProperty: "3 patents (granted). Proprietary strain library.",
      priorSupport: "Innosuisse R&D grant (CHF 200K). Current FONGIT resident.",
      researchOrgs: ["EPFL", "Campus Biotech"],
    },
    fongitFit: {
      genevaStatus: ["Based in Geneva"],
      permitDetails: "Swiss C permit.",
      howCanFongitHelp: "Scaling production. Preparing Series A. Access to international investor network.",
      supportSeeking: ["Access to Financing", "Coaching", "Incubator Hosting"],
      referralSource: "Already in FONGIT program, applying for continued support.",
      backupEmail: "lukas.m@proton.me",
    },
    documents: {
      pitchDeckUrl: "/uploads/bioforge-series-a-deck.pdf",
      additionalDocsUrl: "/uploads/bioforge-financials.xlsx",
      productVideoUrl: "https://youtube.com/watch?v=example4",
      teamVideoUrl: "https://youtube.com/watch?v=example4b",
    },
    status: "accepted",
    score: 91,
    internalNotes: "Exceptional progress. Strong revenue growth. Recommend continued full support.",
    submittedAt: "2026-02-15T11:00:00Z",
    updatedAt: "2026-02-18T14:00:00Z",
  },
  {
    id: "app-005",
    company: {
      name: "CryptoCompliance",
      website: "https://cryptocompliance.io",
      shortDescription: "Automated compliance reporting for crypto exchanges",
      location: "Zurich, Switzerland",
      foundedDate: "2025-06",
      stage: "Users",
      revenueLast30d: "CHF 1,200",
      revenueLast12m: "CHF 8,000",
      detailedDescription: "SaaS platform automating MiCA and FINMA compliance reports for crypto businesses.",
      differentiation: "Only tool covering both EU MiCA and Swiss FINMA requirements in one dashboard.",
      isIncorporated: "Yes",
      customerTypes: ["B2B"],
      productChannels: ["Desktop", "API"],
      markets: "FinTech, RegTech, Crypto",
    },
    team: [
      {
        id: "tm-006",
        firstName: "Elena",
        lastName: "Vasquez",
        email: "elena@cryptocompliance.io",
        role: "CEO",
        description: "Former compliance officer at a major Swiss bank. JD from University of Zurich.",
        skills: "Compliance, Crypto Regulation, Legal",
        amazingBuild: "Built internal compliance automation at her previous bank, saving 2000 analyst hours/year.",
        linkedin: "https://linkedin.com/in/elenavasquez",
        phone: "+41 78 678 9012",
      },
    ],
    project: {
      problemStatement: "Crypto exchanges spend CHF 500K+/year on compliance. Manual processes lead to errors and regulatory risk.",
      differentiation: "Dual MiCA + FINMA coverage. Automated report generation. Real-time regulatory updates.",
      statusAchievements: "8 beta users. 2 paying clients. Seed round discussions ongoing.",
      raisingMoney: "Planning to soon",
      totalRaised: "CHF 80,000",
      runwayMonths: "6",
      investors: "Personal savings + friends & family round",
    },
    marketIP: {
      intellectualProperty: "Proprietary compliance rule engine. No patents.",
      priorSupport: "None.",
      researchOrgs: ["None"],
    },
    fongitFit: {
      genevaStatus: ["Willing to relocate to Geneva"],
      permitDetails: "Swiss C permit. Currently in Zurich, willing to relocate for Geneva's international finance ecosystem.",
      howCanFongitHelp: "Access to Geneva's finance and international organization network.",
      supportSeeking: ["Coaching", "Innovation Community", "Access to Financing"],
      referralSource: "Swiss Startup Association event.",
      backupEmail: "elena.v@gmail.com",
    },
    documents: {
      pitchDeckUrl: "/uploads/cryptocompliance-deck.pdf",
      additionalDocsUrl: null,
      productVideoUrl: "",
      teamVideoUrl: "",
    },
    status: "rejected",
    score: 42,
    internalNotes: "Product overlap with existing Zurich-based solutions. Geneva relocation rationale weak. Suggested applying to F10 Zurich instead.",
    submittedAt: "2026-02-10T09:20:00Z",
    updatedAt: "2026-02-14T10:00:00Z",
  },
  {
    id: "app-006",
    company: {
      name: "AgroVision",
      website: "https://agrovision.ai",
      shortDescription: "Computer vision for vineyard disease detection",
      location: "Geneva, Switzerland",
      foundedDate: "2025-08",
      stage: "Prototype",
      revenueLast30d: "0",
      revenueLast12m: "0",
      detailedDescription: "Drone-mounted cameras with real-time ML inference to detect grapevine diseases before visible symptoms.",
      differentiation: "Sub-centimeter resolution disease mapping. 3 days advance warning vs. visual inspection.",
      isIncorporated: "In Progress",
      customerTypes: ["B2B"],
      productChannels: ["Mobile", "Hardware", "API"],
      markets: "AgriTech, AI, Computer Vision",
    },
    team: [
      {
        id: "tm-007",
        firstName: "Pierre",
        lastName: "Fontaine",
        email: "pierre@agrovision.ai",
        role: "CEO & Founder",
        description: "MSc Computer Vision from EPFL. Family vineyard background in Lavaux.",
        skills: "Computer Vision, Drones, Viticulture",
        amazingBuild: "Won EPFL best thesis award for real-time crop disease detection model.",
        linkedin: "https://linkedin.com/in/pierrefontaine",
        phone: "+41 79 789 0123",
      },
    ],
    project: {
      problemStatement: "Swiss vineyards lose CHF 80M/year to preventable diseases. Manual inspection misses early-stage infections.",
      differentiation: "On-device ML inference (no cloud needed). Works in low-light Swiss climate conditions.",
      statusAchievements: "Working prototype tested on 3 vineyards in Lavaux. 95% disease detection accuracy in trials.",
      raisingMoney: "Not yet",
      totalRaised: "CHF 30,000",
      runwayMonths: "4",
      investors: "Personal savings + EPFL innovation grant",
    },
    marketIP: {
      intellectualProperty: "Proprietary trained models. Patent in preparation for on-device inference method.",
      priorSupport: "EPFL Innovation Grant (CHF 30K).",
      researchOrgs: ["EPFL"],
    },
    fongitFit: {
      genevaStatus: ["Based in Geneva"],
      permitDetails: "Swiss citizen.",
      howCanFongitHelp: "Need help incorporating, building a business plan, and connecting with agricultural investors.",
      supportSeeking: ["Project Initiation", "Coaching", "Access to Financing"],
      referralSource: "EPFL Innovation Office.",
      backupEmail: "p.fontaine@proton.me",
    },
    documents: {
      pitchDeckUrl: "/uploads/agrovision-deck.pdf",
      additionalDocsUrl: "/uploads/agrovision-trial-results.pdf",
      productVideoUrl: "https://youtube.com/watch?v=example6",
      teamVideoUrl: "",
    },
    status: "new",
    score: null,
    internalNotes: "",
    submittedAt: "2026-03-01T16:45:00Z",
    updatedAt: "2026-03-01T16:45:00Z",
  },
  {
    id: "app-007",
    company: {
      name: "SolarWeave",
      website: "https://solarweave.ch",
      shortDescription: "Textile-integrated solar cells for building facades",
      location: "Geneva, Switzerland",
      foundedDate: "2024-05",
      stage: "Prototype",
      revenueLast30d: "0",
      revenueLast12m: "CHF 15,000",
      detailedDescription: "Flexible solar cells woven into architectural textiles for building-integrated photovoltaics.",
      differentiation: "Aesthetically invisible solar power. 12% efficiency in textile form factor (industry first).",
      isIncorporated: "Yes",
      customerTypes: ["B2B"],
      productChannels: ["Hardware"],
      markets: "CleanTech, Architecture, Materials Science",
    },
    team: [
      {
        id: "tm-008",
        firstName: "Nina",
        lastName: "Petrov",
        email: "nina@solarweave.ch",
        role: "CEO & Co-Founder",
        description: "Materials scientist, 10 years in solar cell R&D at CSEM.",
        skills: "Photovoltaics, Materials Science, Product Development",
        amazingBuild: "Co-authored 8 patents on thin-film solar technology at CSEM.",
        linkedin: "https://linkedin.com/in/ninapetrov",
        phone: "+41 79 890 1234",
      },
    ],
    project: {
      problemStatement: "Buildings account for 40% of energy consumption. Rooftop solar alone can't meet net-zero goals. Facades are untapped.",
      differentiation: "Only company achieving >10% efficiency in textile-integrated PV. Partnerships with 2 Swiss architecture firms.",
      statusAchievements: "Working prototypes installed on 2 buildings. CHF 15K in pilot revenue. BFE grant awarded.",
      raisingMoney: "Yes, actively",
      totalRaised: "CHF 150,000",
      runwayMonths: "12",
      investors: "BFE grant (CHF 100K), FONGIT Innovation Fund (CHF 50K)",
    },
    marketIP: {
      intellectualProperty: "3 patents (2 granted, 1 pending). Licensed base technology from CSEM.",
      priorSupport: "BFE grant (CHF 100K). FIF grant (CHF 50K). Current FONGIT resident.",
      researchOrgs: ["EPFL", "Campus Biotech"],
    },
    fongitFit: {
      genevaStatus: ["Based in Geneva"],
      permitDetails: "Swiss C permit.",
      howCanFongitHelp: "Preparing for Series A. Need support with investor introductions and scaling manufacturing.",
      supportSeeking: ["Access to Financing", "Coaching", "Incubator Hosting"],
      referralSource: "Already in FONGIT program.",
      backupEmail: "nina.petrov@proton.me",
    },
    documents: {
      pitchDeckUrl: "/uploads/solarweave-deck.pdf",
      additionalDocsUrl: "/uploads/solarweave-bfe-report.pdf",
      productVideoUrl: "https://youtube.com/watch?v=example7",
      teamVideoUrl: "https://youtube.com/watch?v=example7b",
    },
    status: "accepted",
    score: 88,
    internalNotes: "Excellent deep tech with clear path to market. Strong IP portfolio. Continue full support.",
    submittedAt: "2026-01-28T13:30:00Z",
    updatedAt: "2026-02-01T11:00:00Z",
  },
];

export const MOCK_APPLICATIONS: Application[] = RAW_APPLICATIONS.map((app) => ({
  ...app,
  scoreBreakdown: scoreApplication(app).scoreBreakdown,
  aiSummary: null,
}));
